export interface Data {
  "University": string,
  "Name": string,
  "Major": string,
  "Bio": string,
  "Grade": string,
  "Political Leaning": string,
  "I'm not interested in artistic things (music, plays, poetry, etc.)": string,
  "I always tell people the truth, even if it might hurt": string,
  "Left brain or right brain": string,
  "I laugh a lot": string,
  "I don't like drawing attention to myself": string,
  "I tend to be quiet": string,
  "I like playing with abstract ideas": string,
  "I frequently plan things out in advance": string,
}