import ButtonGroup from "../components/ButtonGroup";
import InputDropdown from "../components/InputDropdown";
import InputField from "../components/InputField";
import Multiselect from "../components/Multiselect";
import Scale from "../components/Scale";
import { Props } from "../types/Props";

export const questions: Props[] = [
  {
    label: 'Name',
    leftExtreme: '',
    rightExtreme: '',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: InputField,
  },
  {
    label: 'Major',
    leftExtreme: '',
    rightExtreme: '',
    options: [{ name: 'Computer Science' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: InputDropdown,
  },
  {
    label: 'Bio',
    leftExtreme: '',
    rightExtreme: '',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: InputField,
  },
  {
    label: 'Grade',
    leftExtreme: '',
    rightExtreme: '',
    options: [{ name: 'Frosh' }, { name: 'Soph' }, { name: 'Junior' }, { name: 'Senior' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: ButtonGroup,
  },
  {
    label: 'Political Leaning',
    leftExtreme: 'Very liberal',
    rightExtreme: 'Very conservative',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `I'm not interested in artistic things (music, plays, poetry, etc.)`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: 'I always tell people the truth, even if it might hurt',
    leftExtreme: 'Stongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `Left brain or right brain`,
    leftExtreme: 'Left',
    rightExtreme: 'Right',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `I laugh a lot`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `I don't like drawing attention to myself`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `I tend to be quiet`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `I like playing with abstract ideas`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `Staying physically fit is very important to me`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `I frequently plan things out in advance`,
    leftExtreme: 'Strongly disagree',
    rightExtreme: 'Strongly agree',
    options: [{ name: '' }],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Scale,
  },
  {
    label: `Interests`,
    leftExtreme: '',
    rightExtreme: '',
    options: [
      { name: "Musical instrument" },
      { name: "Sports" },
      { name: "Working out" },
      { name: "Cooking" },
      { name: "Baking" },
      { name: "Video games" },
      { name: "Eating food" },
      { name: "Coding" },
      { name: "Reading" },
      { name: "Watching movies" },
      { name: "Arts & crafts" },
      { name: "Climbing" },
      { name: "Anime" },
      { name: "Writing" },
      { name: "Hiking" },
    ],
    hideTitle: false,
    link: '',
    linkText: '',
    component: Multiselect,
  }
]

export const PageTitles = [];